CREATE DATABASE EMP;
USE EMP;
CREATE TABLE EMPP(
E_ID int not null,
 E_NAME varchar(20) not null,
 AGE int not null,
 SALARY int not null,
 PRIMARY KEY(E_ID)
 );
INSERT INTO EMPP(E_ID,E_NAME,AGE,SALARY) VALUES(101,"Arun",20,9000);
INSERT INTO EMPP(E_ID,E_NAME,AGE,SALARY) VALUES(102,"Shane",28,8000);
INSERT INTO EMPP(E_ID,E_NAME,AGE,SALARY) VALUES(103,"Rohan",23,6000);
INSERT INTO EMPP(E_ID,E_NAME,AGE,SALARY) VALUES(104,"Scott",34,10000);
INSERT INTO EMPP(E_ID,E_NAME,AGE,SALARY) VALUES(105,"Tiger",25,8000);
INSERT INTO EMPP(E_ID,E_NAME,AGE,SALARY) VALUES(106,"Alex",30,7000);
INSERT INTO EMPP(E_ID,E_NAME,AGE,SALARY) VALUES(107,"Abhi",29,8000);
SELECT * FROM EMPP;
SELECT COUNT(*) FROM EMPP;
SELECT MAX(AGE) FROM EMPP;
SELECT MIN(AGE) FROM EMPP;
SELECT SUM(AGE) FROM EMPP;
SELECT AVG(AGE) FROM EMPP;
CREATE VIEW AGES AS SELECT AGE FROM EMPP;
SELECT * FROM AGES;
SELECT SALARY FROM EMPP GROUP BY SALARY;
SELECT SALARY FROM EMPP ORDER BY SALARY ASC;
SELECT SALARY FROM EMPP ORDER BY SALARY DESC
